[package]
name = "winit_demo"
version = "0.1.2"
edition = "2021"
publish = false

[dependencies]
futures = "0.3"
wgs_core = { path = "../wgs_core" }
wgs_runtime_wgpu = { path = "../wgs_runtime_wgpu" }
winit = "0.28"
